### ISSUE TITLE
weights of bins outside ROI

### ISSUE THREAD

**Issue by golova-n** [ArtemLuzhin/C-TALE-Normalization#4]
May be I do not understand something, but, it seems, that in the current version of the script when weights of bins outside ROI are estimated, mult_factor is not taken into account. That is why, I guess, pixels outside ROI are always under-coloured after balancing (even if mult_factor is set to 100). Is it supposed to work this way?

**Comment by Phlya** [comment]
As far as I remember, multiplication was taken into account separately here, but I will check next week if you see under-colouring... Actually, multiplication would be easiest to do by setting weights of bins outside to mult_factor, I think now!
